[package]
name = "morse-lib"
description = "Library for coding/decoding Morse Code with multilanguage support"
version = "0.4.1"
edition = "2021"
license = "GPL-3.0-or-later"
repository = "https://github.com/NazarK0/morse-lib"
homepage = "https://github.com/NazarK0/morse-lib"
keywords = ["morse", "parser", "encoder"]
categories = ["encoding", "parsing"]
resolver = "2"

[dependencies]
rodio = {version = "0.19.0", optional = true}

[features]
default = ["international"]
international = []
custom = []
audio = ["dep:rodio"]

[package.metadata.docs.rs]
all-features = true
